destination: ./_site
pygments:    true
markdown:    rdiscount
exclude:     Rakefile Gemfile Gemfile.lock
permalink:   /:year/:month/:title.html
rdiscount:
  smart:     true
url:         http://notes.exomel.com
